### ISSUE TITLE
发布文章时不要跳转回文章列表

### ISSUE THREAD

**Issue by HJDev** [firekylin/firekylin#381]
好不容易找到一个这么好用的国产MarkDown 博客系统，非常喜欢，已经迫不及待想将自己的Ghost迁移过来了。刚使用了一下，发现一点小问题。

- [x] Fixed in #382.我在编辑文章的时候，看到下面可以下拉扩大编辑区域，但我下拉后，编辑区域却并没有跟着变大，留下了一个空白的区域，而编辑预览区域(右侧)是变大了的。
- [ ] See #356. 希望可以在编辑文章后，可以提供一个预览的选项，让我们小白用户预览自己刚写得文章
- [ ] #383. 我每次点`保存草稿`和`发布文章`后，都会给我跳到文章列表，其实我只是想看下发布后的预览效果，但我每次点击这两个按钮都给我返回到了文章列表，然后再需要点击进入文章编辑页来编辑。希望可以在点击这两个按钮的时候不用跳转，或者提供一个选项供用户选择。
- [ ] #383. 希望可以在用户点击`发布文章`按钮后，可以弹出一个文章的链接，（可以参考`Ghost`在左下角弹出一个文章链接，过一会儿再消失的方式），方便用户进入这篇文章。

**Comment by ddhhz** [comment]
3 & 4: 如果需要实现可以 replace 以下两行 with some kind of [Toaster](https://tomchentw.github.io/react-toastr/) 或者其他通知组件。
https://github.com/firekylin/firekylin/blob/a3708d3e82bc92ef4b8573417985757f74704334/www/static/src/admin/component/post_create/index.jsx#L156
https://github.com/firekylin/firekylin/blob/85059baeb67a3c9186ccc5789062cdd232c38192/www/static/src/admin/component/page_create.jsx#L45

**Comment by lizheming** [comment]
后面几条本质上应该是同一个用户体验的问题，我们会通过增加预览的方式来解决，感谢反馈！
